# Generated by Django 5.1.2 on 2024-11-08 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracks',
            name='country',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_date', models.DateField()),
                ('race_number', models.IntegerField()),
                ('drf_tracks_import', models.BooleanField(default=False)),
                ('day_evening', models.CharField(blank=True, choices=[('D', 'Day'), ('E', 'Evening')], max_length=1)),
                ('final', models.BooleanField(blank=True)),
                ('drf_entries_import', models.BooleanField(default=False)),
                ('post_time', models.DateTimeField(blank=True)),
                ('age_restriction', models.CharField(blank=True, choices=[('02', '2 yo'), ('03', '3 yo'), ('04', '4 yo'), ('05', '5 yo'), ('06', '6 yo'), ('07', '7 yo'), ('08', '8 yo'), ('09', '9 yo'), ('23', "2 & 3 yo's"), ('2U', "2 yo's & up"), ('34', "3 & 4 yo's"), ('35', "3, 4, & 5 yo's"), ('36', "3, 4, 5, & 6 yo's"), ('3U', "3 yo's & up"), ('45', "4 & 5 yo's"), ('46', "4, 5, & 6 yo's"), ('47', "4, 5, 6, & 7 yo's"), ('4U', "4 yo's & up"), ('56', "5 & 6 yo's"), ('57', "5, 6, & 7 yo's"), ('58', "5, 6, 7, & 8 yo's"), ('59', "5, 6, 7, 8, & 9 yo's"), ('5U', "5 yo's & up"), ('67', "6 & 7 yo's"), ('68', "6, 7, & 8 yo's"), ('69', "6, 7, 8, & 9 yo's"), ('6U', "6 yo's & up"), ('78', "7 & 8 yo's"), ('79', "7, 8, & 9 yo's"), ('7U', "7 yo's & up"), ('8U', "8 yo's & up"), ('9U', "9 yo's & up")], max_length=2)),
                ('sex_restiction', models.CharField(blank=True, choices=[('N', 'Open'), ('A', 'C & G (colts and geldings)'), ('B', 'F & M (fillies and mares)'), ('C', 'C (colts)'), ('D', 'C & F (colts and fillies)'), ('E', 'F & G (fillies and geldings)'), ('F', 'F (fillies)'), ('G', 'G (geldings)'), ('H', 'H (horses only)'), ('M', 'M (mares only)')], max_length=1)),
                ('minimum_claiming_price', models.FloatField(blank=True)),
                ('maximum_claiming_price', models.FloatField(blank=True)),
                ('distance', models.FloatField(blank=True)),
                ('purse', models.IntegerField(blank=True)),
                ('wager_text', models.CharField(max_length=255, null=True)),
                ('breed', models.CharField(blank=True, choices=[('TB', 'Thoroughbred'), ('QH', 'Quarter Horse'), ('AR', 'Arabian'), ('PT', 'Paint'), ('MX', 'Mixed Breeds')], max_length=2)),
                ('cancelled', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.tracks')),
            ],
        ),
    ]
