# Generated by Django 5.1.2 on 2024-11-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0004_alter_races_age_restriction_alter_races_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='sex_restiction',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'C & G (colts and geldings)'), ('B', 'F & M (fillies and mares)'), ('C', 'C (colts)'), ('D', 'C & F (colts and fillies)'), ('E', 'F & G (fillies and geldings)'), ('F', 'F (fillies)'), ('G', 'G (geldings)'), ('H', 'H (horses only)'), ('M', 'M (mares only)')], max_length=1, null=True),
        ),
    ]
