# Generated by Django 5.1.2 on 2024-11-08 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0005_alter_races_sex_restiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jockeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('drf_jockey_id', models.IntegerField(null=True)),
                ('drf_jockey_type', models.CharField(blank=True, max_length=2)),
                ('alias', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('drf_trainer_id', models.IntegerField(null=True)),
                ('drf_trainer_type', models.CharField(blank=True, max_length=2)),
                ('alias', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.IntegerField(null=True)),
                ('dam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_of_dam', to='horsemen.horses')),
                ('dam_sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grandchildren', to='horsemen.horses')),
                ('sire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_of_sire', to='horsemen.horses')),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_number', models.CharField(max_length=3)),
                ('post_position', models.IntegerField()),
                ('drf_entries_import', models.BooleanField(default=False)),
                ('scratch_flag', models.BooleanField(default=False)),
                ('medication', models.CharField(blank=True, max_length=7, null=True)),
                ('equipment', models.CharField(blank=True, max_length=17, null=True)),
                ('comments', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.races')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.horses')),
                ('jockey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.jockeys')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.trainers')),
            ],
        ),
    ]
