# Generated by Django 5.1.2 on 2024-11-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0008_alter_horses_registration_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='scratch_flag',
        ),
        migrations.AddField(
            model_name='entries',
            name='scratch_indicator',
            field=models.CharField(default='', max_length=1),
        ),
    ]
