# Generated by Django 5.1.2 on 2024-11-11 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0012_entries_equibase_speed_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='jockey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horsemen.jockeys'),
        ),
        migrations.AlterField(
            model_name='entries',
            name='post_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='program_number',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='horsemen.trainers'),
        ),
    ]
