# Generated by Django 5.1.2 on 2024-11-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0015_remove_horses_horse_results_scraped_for_race_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='equibase_horse_entries_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='races',
            name='race_surface',
            field=models.CharField(choices=[('D', 'Dirt'), ('T', 'Turf')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_date', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('time_seconds', models.FloatField()),
                ('note', models.CharField(max_length=255)),
                ('workout_rank', models.IntegerField()),
                ('workout_total', models.IntegerField()),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.horses')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.tracks')),
            ],
        ),
    ]
