# Generated by Django 5.1.2 on 2024-11-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0018_races_eqb_chart_import'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracks',
            name='equibase_chart_name',
        ),
        migrations.AddField(
            model_name='entries',
            name='drf_results_import',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='place_payoff',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='show_payoff',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='entries',
            name='win_payoff',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='condition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='races',
            name='drf_results_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='races',
            name='off_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='scratch_indicator',
            field=models.CharField(choices=[('N', 'Not Scratched'), ('A', 'Also-Eligible'), ('E', 'Early'), ('G', 'Gate'), ('M', 'Main-Track-Only'), ('O', 'Off-Turf'), ('S', 'Stewards'), ('T', 'Trainer'), ('V', 'Veterinarian'), ('U', 'Unknown')], default='N', max_length=1),
        ),
        migrations.CreateModel(
            name='Payoffs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wager_type', models.CharField(choices=[('0', 'Choose 6'), ('C', 'Classix'), ('Z', 'Consolation Double'), ('M', 'Consolation Pick 3'), ('8', 'Countdown'), ('D', 'Daily Double'), ('E', 'Exacta'), ('J', 'Exactor'), ('N', 'Future Wager'), ('X', 'Grand Slam'), ('H', 'Head2Head'), ('P', 'Jockey Challenge'), ('V', 'Odd or Even'), ('O', 'Omni'), ('F', 'Perfecta'), ('G', 'Perfector'), ('I', 'Pick 10'), ('3', 'Pick 3'), ('4', 'Pick 4'), ('5', 'Pick 5'), ('6', 'Pick 6'), ('7', 'Pick 7'), ('9', 'Pick 9'), ('L', 'Place Pick All'), ('Q', 'Quinella'), ('1', 'Roulette'), ('Y', 'Super Bet'), ('B', 'Super Tri'), ('S', 'Superfecta'), ('U', 'Tri Super'), ('A', 'Triactor'), ('T', 'Trifecta'), ('R', 'Triple'), ('W', 'Twin Trifecta'), ('2', 'Two in the Money'), ('K', 'Win Four')], max_length=1)),
                ('winning_numbers', models.CharField(max_length=255)),
                ('total_pool', models.FloatField(default=0)),
                ('payoff_amount', models.FloatField(default=0)),
                ('base_amount', models.FloatField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.races')),
            ],
        ),
    ]
