# Generated by Django 5.1.2 on 2024-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0020_alter_payoffs_wager_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='equibase_horse_entries_scraped',
            new_name='equibase_horse_entries_import',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='equibase_horse_results_scraped',
            new_name='equibase_horse_results_import',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='eqb_chart_import',
            new_name='equibase_chart_import',
        ),
        migrations.RenameField(
            model_name='races',
            old_name='eqb_entries_import',
            new_name='equibase_entries_import',
        ),
        migrations.RemoveField(
            model_name='entries',
            name='drf_results_import',
        ),
        migrations.RemoveField(
            model_name='races',
            name='final',
        ),
        migrations.AddField(
            model_name='races',
            name='race_type',
            field=models.CharField(choices=[('ALW', 'Allowance race'), ('AOC', 'Allowance/Optional Claiming'), ('CLH', 'Claiming Handicap'), ('CLM', 'Claiming'), ('CST', 'Claiming Stakes'), ('HCP', 'Handicap'), ('MAT', 'Match Race'), ('MCL', 'Maiden Claiming'), ('MOC', 'Maiden Optional Claiming'), ('MSA', 'Maiden Starter Allowance'), ('MSW', 'Maiden Special Weight'), ('MST', 'Maiden Stakes'), ('OCH', 'Optional Claiming Handicap'), ('OCL', 'Optional Claiming'), ('SHP', 'Starter Handicap'), ('SOC', 'Starter/Optional Claiming'), ('SST', 'Starter Stakes'), ('STK', 'Stakes'), ('STR', 'Starter Allowance'), ('TRL', 'Trial'), ('WCL', 'Waiver Claiming'), ('WMC', 'Waiver Maiden Claiming'), ('ALWFL', 'Allowance Final'), ('AWT', 'Allowance Trial'), ('CAN', 'Cancelled'), ('CHM', 'Championship'), ('CLS', 'Claiming Stakes'), ('CLT', 'Claiming Stakes Trial'), ('CON', 'Consolation'), ('CST', 'Claiming Stakes/Trial'), ('DBY', 'Derby'), ('DBYFL', 'Derby Final'), ('DCN', 'Derby Consolation'), ('DTR', 'Derby Trial'), ('EXH', 'Exhibition'), ('FCN', 'Futurity Consolation'), ('FNL', 'Final'), ('FTR', 'Futurity Trial'), ('FUT', 'Futurity'), ('FUTFL', 'Futurity Final'), ('HDS', 'Handicap Stakes'), ('IHS', 'Invitational Handicap Stakes'), ('INH', 'Invitational Handicap'), ('INS', 'Invitational Stakes'), ('INV', 'Invitational'), ('MCL', 'Maiden Claiming'), ('MCN', 'Maturity Consolation'), ('MATFL', 'Maturity Final'), ('MCH', 'Match Race'), ('MDN', 'Maiden'), ('MDT', 'Maiden Trial'), ('MOC', 'Maiden Optional Claiming'), ('MSA', 'Maiden Starter Allowance'), ('MTR', 'Maturity Trial'), ('OCL', 'Optional Claiming'), ('SCN', 'Stakes Consolation'), ('SHP', 'Starter Handicap'), ('SOC', 'Starter Optional Claiming'), ('SPC', 'Speed Index Consolation'), ('SPF', 'Speed Index Final'), ('SPI', 'Speed Index Race'), ('SPT', 'Speed Index Trial'), ('STA', 'Starter Allowance'), ('STK', 'Stakes'), ('STR', 'Stakes Trial'), ('TRL', 'Trials'), ('UNK', 'Unknown Race Type'), ('WCL', 'Waiver Claiming'), ('ZRC', 'Cancelled Race')], max_length=5, null=True),
        ),
    ]
