# Generated by Django 5.1.2 on 2024-11-15 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0022_entries_comment_alter_races_age_restriction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='races',
            old_name='sex_restiction',
            new_name='sex_restriction',
        ),
    ]
