# Generated by Django 5.1.2 on 2024-11-30 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0025_remove_jockeys_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splitcallvelocities',
            name='race',
        ),
        migrations.AddField(
            model_name='splitcallvelocities',
            name='entry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='horsemen.entries'),
            preserve_default=False,
        ),
    ]
