# Generated by Django 5.1.2 on 2024-11-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0027_alter_splitcallvelocities_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splitcallvelocities',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsemen.entries'),
        ),
    ]
