# Generated by Django 5.1.2 on 2024-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsemen', '0028_alter_splitcallvelocities_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='hurdles',
            field=models.BooleanField(default=False),
        ),
    ]
